### ISSUE TITLE
How to use Rest API in C# for uploading topology in Azure Stoem HDInsight

### ISSUE THREAD

**Issue by Shriyanshmit** [Blackmist/eventhub-storm-hybrid#7]
Hi,
Please let me know details about hoe to implement Rest API in C# for uploading topology in Azure Stoem HDInsight with any example or demo.

Thanks
Shreyansh

**Comment by Blackmist** [comment]
I think this (https://github.com/hdinsight/hdinsight-storm-examples/tree/master/tools/SCPNetTopologySubmitter) is what you are looking for. It's used by the hdinsight/hdinsight-storm-examples project to submit the examples to a Storm cluster.

Forgot to add that you must first create a package and spec file for the topology. See the createscppackage.ps1 and createscpspec.ps1 files (and others) at https://github.com/hdinsight/hdinsight-storm-examples/tree/master/scripts/scpnet. The REST API for submitting the SCP.NET-based topologies expects both of these files.

**Comment by Shriyanshmit** [comment]
When i try to upload(Event Hub Writer) topology it shows error:

4/10/2015 3:55:14 PM    Failed to submit topology :
4/10/2015 3:55:14 PM    StatusCode: BadRequest
"Version: 0.9.5.42
Compiling C:\apps\dist\SCPAPI\SCPAPI\App_Data\EventHubWriter.spec...
Exception in thread "main" java.lang.ClassNotFoundException: com.microsoft.eventhubs.bolt.EventHubBoltConfig, compiling:(EventHubWriter.clj:30:54)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$NewExpr$Parser.parse(Compiler.java:2499)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$MapExpr.parse(Compiler.java:2879)
    at clojure.lang.Compiler.analyze(Compiler.java:6369)
    at clojure.lang.Compiler.analyze(Compiler.jav
a:6322)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$MapExpr.parse(Compiler.java:2879)
    at clojure.lang.Compiler.analyze(Compiler.java:6369)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.access$100(Compiler.java:37)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:529)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
    at clojure.la
ng.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler.compile1(Compiler.java:7148)
    at clojure.lang.Compiler.compile(Compiler.java:7219)
    at clojure.lang.RT.compile(RT.java:398)
    at clojure.lang.RT.load(RT.java:438)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)

```
at clojure.core$load_one.invoke(core.clj:5336)

at clojure.core$compile$fn__5023.invoke(core.clj:5541)
at clojure.core$compile.invoke(core.clj:5540)
at user$eval3.invoke(run571838103277442744.clj:1)
at clojure.lang.Compiler.eval(Compiler.java:6619)
at clojure.lang.Compiler.load(Compiler.java:7064)
at clojure.lang.Compiler.loadFile(Compiler.java:7020)
at clojure.main$load_script.invoke(main.clj:294)
at clojure.main$script_opt.invoke(main.clj:356)


at clojure.main$main.doInvoke(main.clj:440)

at clojure.lang.RestFn.invoke(RestFn.java:408)

at clojure.lang.Var.invoke(Var.java:415)
at clojure.lang.AFn.applyToHelper(AFn.java:161)
at clojure.lang.Var.applyTo(Var.java:532)
at clojure.main.main(main.java:37)
```

Caused by: java.lang.ClassNotFoundException: com.microsoft.eventhubs.bolt.EventHubBoltConfig

```
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)

at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)

at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:270)

at clojure.lang.RT.classForName(RT.java:2070)
at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:969)
at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:747)

at clojure.lang.Compiler$NewExpr$Parser.parse(Compiler.java:2494)
at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)

... 59 more
```

Exception in thread "main" 
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at scp.spec.compile$exec_command_BANG_.doInvoke(compile.clj:15)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at scp.spec.compile$make_jar.invoke(compile.clj:61)
    at scp.spec.compile$_main.invoke(compile.clj:112)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at scp.spec.compile.main(Unknown Source)

Submitting topology EventHubWriter...
Error: Could not find or load main class EventHubWriter

"

**Comment by Blackmist** [comment]
java.lang.ClassNotFoundException: com.microsoft.eventhubs.bolt.EventHubBoltConfig means it's not finding the Java class. When you submit the topology through Visual Studio, be sure to expand the "Additional Configuration" entry, check "Java File Paths", and specify the path to the directory that contains the eventhubs-storm-spout-0.9-jar-with-dependencies.jar file.

**Comment by Shriyanshmit** [comment]
When i try to upload topology using this code it throws an error.

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SCPNetTopologySubmitter.Program.<TopologySubmit>d__4.MoveNext() in d:\R&D\Storm\EventHUbStorm\hdinsight-storm-examples-master\tools\SCPNetTopologySubmitter\Program.cs:line 132
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at SCPNetTopologySubmitter.Program.Main(String[] args) in d:\R&D\Storm\EventHUbStorm\hdinsight-storm-examples-master\tools\SCPNetTopologySubmitter\Program.cs:line 48
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SCPNetTopologySubmitter.Program.<TopologySubmit>d__4.MoveNext() in d:\R&D\Storm\EventHUbStorm\hdinsight-storm-examples-master\tools\SCPNetTopologySubmitter\Program.cs:line 132
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---

Thanks
Shreyansh

**Comment by Blackmist** [comment]
I would recommend opening an issue in the https://github.com/hdinsight/hdinsight-storm-examples project, since that's where the SCPNetTopologySubmitter exists. Any problems with it should be reported, and fixed, within that project.
